---
dataset:
  dataset: ActivityNetGraph
  feature_path: "/home/zhaoyang/data/activity-c3d"
  word_dim: 300
  frame_dim: 500
  max_num_words: 20
  max_num_frames: &max_num_frames 256
  target_stride: 2
  train_data: data/activitynet/train_data.json
  test_data: data/activitynet/test_data.json
  val_data: data/activitynet/val_data.json
  vocab_path: data/activitynet/glove_model.bin
train:
  lr: 0.0008
  weight_decay: 1.0e-07
  warmup_updates: 200
  warmup_init_lr: 1.0e-07
  batch_size: 32
  max_num_epochs: 20
  model_saved_path: checkpoints/activitynet/weak
  topK: 32
  norm1: 0.1
  intra: 0.1
  norm2: 0.01
model:
  name: WeaklyGraph
  filter_branch: true
  VideoEncoder:
    name: FramePyramid
    input_size: 500
    hidden_size: 256
    max_num_frames: *max_num_frames
  QueryEncoder:
    name: QueryEncoder
    input_size: 300
    hidden_size: 256
    gru:
      num_layers: 1
      bidirectional: true
  Fusion:
    name: BetterFusion
    hidden_size: 256
    gru:
      num_layers: 1
      bidirectional: true
    SparsePropMaxPool:
      num_scale_layers: [16, 8, 8]
      num_layers: 64
  Scorer:
    name: MapConv
    input_size: 256
    hidden_sizes: [256]
    kernel_sizes: [5]
    strides: [1]
    paddings: [2]
    dilations: [1]
  Filter:
    hidden_size: 256